FileVersion = 1

[Project]
Name = "Chipmunk2D-beef"
TargetType = "BeefLib"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2022\\bin\\chipmunk2dDebug.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2022\\bin\\chipmunk2dRelease.lib"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2022\\bin\\chipmunk2dRelease.lib"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2022\\bin\\chipmunk2dRelease.lib"]

[Configs.Debug.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx-x64\\bin\\libchipmunk2dDebug.a"]

[Configs.Release.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx-x64\\bin\\libchipmunk2dRelease.a"]

[Configs.Paranoid.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx-x64\\bin\\libchipmunk2dRelease.a"]

[Configs.Test.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx-x64\\bin\\libchipmunk2dRelease.a"]

[Configs.Debug.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libchipmunk2dDebug.a"]

[Configs.Release.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libchipmunk2dRelease.a"]

[Configs.Paranoid.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libchipmunk2dRelease.a"]

[Configs.Test.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libchipmunk2dRelease.a"]
